### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by justyy** [klugjo/hexo-theme-phantom#1]
where i start server , the console will show this. is this right?
![image](https://cloud.githubusercontent.com/assets/7438323/14204391/93e49bb2-f836-11e5-9a6a-1fb962aa5a9a.png)

**Comment by justyy** [comment]
i forget install the hexo-renderer-sass.....

**Comment by klugjo** [comment]
Thanks for reporting, added it to the README
