### ISSUE TITLE
Error finding main.css

### ISSUE THREAD

**Issue by benjamin-kirkbride** [klugjo/hexo-theme-phantom#10]
I'm stumped on this one. For whatever reason, the `main.css` seems to be pulling from the wrong place. there is a `main.css` in `css/` but not in `sass/`.

> 10:06:27 [error] 13#13: *1 open() "/usr/share/nginx/html/public/sass/main.css" failed (2: No such file or directory), client: 10.1.1.234, server: localhost, request: "GET /sass/main.css HTTP/1.1", host: "10.1.0.10", referrer: "http://10.1.0.10

**Comment by benjamin-kirkbride** [comment]
UPDATE: If I run `cp public/css/main.css /public/sass/` then it works perfectly. I feel it's safe to say that's not a permanent solution. My understanding of the problem so far is that for some reason the (theme? web server? hexo?) is looking in the `sass/` dir instead of the `css` dir.

**Comment by benjamin-kirkbride** [comment]
Excerpt from index.html:

> ```
>  
> <link rel="stylesheet" href="/sass/main.css">
> 
> 
> 
> 
> 
> 
> ```

**Comment by benjamin-kirkbride** [comment]
So I'm an idiot, ofc. You have to install sass after you run npm install for Hexo. Live and learn.

**Comment by angelofan** [comment]
@klugjo @brian-whitfield 
Same problem, installing sass should be written in the readme.
This is a must-install library for this theme, not a required option for hexo.

**Comment by angelofan** [comment]
Here is the solution:
1. Modify the css reference in `phantom/layout/_partial/head.ejs`.
````
<!-- Custom CSS -->
<%- css('sass/main.css') %>
````
change into
````
<!-- Custom CSS -->
<%- css('css/main.css') %>
````
2. Delete the unnecessary scss folder `phantom/source/sass/` as there is no call in the code.
3. Run
````
$ hexo clean & hexo g
$ hexo s
````
No need to install additional sass packages.
Now, everything works fine.
