### ISSUE TITLE
can't build images folder

### ISSUE THREAD

**Issue by HIKALU-Z** [klugjo/hexo-theme-phantom#11]
hello , I like your theme very much
i build my blog as the doucument .
but after i start server 
in the Chrome devtools it says Failed to load resource and can't find images folder.
my blog's repositories  is [this](https://github.com/HIKALU-Z/white-block/tree/gh-pages)
can you help me to see what's wrong with it?

**Comment by klugjo** [comment]
I think you forgot to specify the root or url of your website in Hexo's main configuration _config.yml

something like

url: http://www.yoursite.com/
root: /

**Comment by klugjo** [comment]
Closing as no response
