### ISSUE TITLE
友情链接

### ISSUE THREAD

**Issue by C0Cx** [klugjo/hexo-theme-phantom#13]
如何添加友情链接

**Comment by klugjo** [comment]
english please :)

**Comment by C0Cx** [comment]
How to add links

**Comment by klugjo** [comment]
What do you mean ?

**Comment by C0Cx** [comment]
friends links

**Comment by klugjo** [comment]
Please consult Hexo official documentation for the basics of adding links

https://hexo.io/

**Comment by C0Cx** [comment]
woo~thank you.But I want to know the template can add this module

**Comment by klugjo** [comment]
What module ?

**Comment by C0Cx** [comment]
Can this theme add the friend chain? Beacuse I failed to add the friend chain to it.

**Comment by C0Cx** [comment]
oh...I am so sorry.I want to konw this question for theme alpha-dust,not this theme.Not this theme.

**Comment by C0Cx** [comment]
My English is poor....so bad..
