### ISSUE TITLE
Fonts not displaying properly

### ISSUE THREAD

**Issue by kellytang** [klugjo/hexo-theme-phantom#17]
The font Source Sans Pro displays properly on my local server, but once deployed to kellytang.github.io, doesn't. What can I do to fix this?

I'm not sure whether FontAwesome (or other fonts used, if any) work properly or not since it's so simple.

**Comment by klugjo** [comment]
Check out the console for error

Mixed Content: The page at 'https://kellytang.github.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,700,900'. This request has been blocked; the content must be served over HTTPS.

Can you try to open main.scss

https://github.com/klugjo/hexo-theme-phantom/blob/master/source/sass/main.scss

and change http to https on line 6 ?

**Comment by kellytang** [comment]
It works! Thank you so much.

I changed \themes\phantom\source\css\main.css line 2 to https as well for safety's sake.
