### ISSUE TITLE
How to disable the background color for the post in mainpage

### ISSUE THREAD

**Issue by cf1497** [klugjo/hexo-theme-phantom#19]
The deafult backgroud color is pink, can I know how can I change the backgroud color of each post in the main page?

**Comment by klugjo** [comment]
I am not sure what pink background you are talking about. Feel free to modify the CSS inside the SASS folder to suit your needs.

**Comment by cf1497** [comment]
Hi, when I add a new post, the new post will display in the main page with a default background color(pink, blue....), which I cannot customized. Can I know how to change the color?
