### ISSUE TITLE
Can we choose the order to display the post?

### ISSUE THREAD

**Issue by wuweijia1994** [klugjo/hexo-theme-phantom#22]
For example, could we choose to display the post in the order of importance instead of the time you creat it?

**Comment by klugjo** [comment]
Sorry for the late reply, I have been busy starting a new job.

you will have to define what is the order of importance in the front matter then you can go here:

https://github.com/klugjo/hexo-theme-phantom/blob/master/layout/index.ejs#L7

And you have access to all the posts, so order them whichever way you like.

**Comment by wuweijia1994** [comment]
Thanks for replying! But I am still a little confused about that. Is there any example of that? For example, I have articles called A and B, and then how to define the order in this "index.ejs" file?

**Comment by klugjo** [comment]
So you want to sort by name ?

**Comment by wuweijia1994** [comment]
No, I want to sort by the importance. But I have no idea how to define the order.

**Comment by klugjo** [comment]
what is importance ? It is not a default hexo parameter

**Comment by wuweijia1994** [comment]
For example, say I have "A" and "B". I write "A" first and normally, it will be in the second place. But I still want it to be the first one in the display. Is it possible to do that?

**Comment by klugjo** [comment]
As I said you need to defined it in front matter then modify the sort order in the file I indicated

**Comment by klugjo** [comment]
https://hexo.io/docs/front-matter.html

**Comment by klugjo** [comment]
for example

first post:

```
title: Hello World
date: 2013/7/13 20:46:25
importance: 1
```

second post:

```
title: Hello World 2
date: 2013/7/13 20:46:25
importance: 2
---
```

then you can do something like
```
<section class="tiles">
    <%
        // Fast array clone
        var sortedPosts = page.posts.slice(0);
        sortedPosts.sort(function(a, b){
          return a.importance < b.importance
        });
    %>
    <% sortedPosts.forEach(function(item, index){ %>
        <%- partial('_partial/article-index', {item: item, index: index}) %>
    <% }); %>
</section>
```

**Comment by wuweijia1994** [comment]
Wow, thank you so much! Now I got it!

**Comment by wuweijia1994** [comment]
Sorry to bother again. I understand what you said, and copy and paste the code. But it still keeps the same order.

/Users/weijiawu/blog/source/_posts/A.md
`---
title: Medical Device for foot pressure
date: 2018-04-03 19:57:46
tags: Sensor
cover_index: /images/Medical Device.jpg
importance: 5
---` 


/Users/weijiawu/blog/source/_posts/B.md
`---
title: Self-Balance Bike with Inverted Pendulum
date: 2018-04-02 12:13:09
tags:
- Control
- Robotics
cover_index: /images/Inverted Pendulum Cover.jpg
importance: 7
---`

/Users/weijiawu/blog/themes/phantom/layout/index.ejs
`<header>
    <h1><%- theme.subtitle_main %></h1>
    <p><%- theme.susbtitle_secondary %></p>
</header>

<section class="tiles">
   <%
       // Fast array clone
       var sortedPosts = page.posts.slice(0);
       sortedPosts.sort(function(a, b){
         return a.importance < b.importance
       });
   %>
   <% sortedPosts.forEach(function(item, index){ %>
       <%- partial('_partial/article-index', {item: item, index: index}) %>
   <% }); %>
</section>

<%- partial('_partial/pagination') %>`

**Comment by wuweijia1994** [comment]
Sorry to bother again. I understand what you said, and copy and paste the code. But it still keeps the same order.

/Users/weijiawu/blog/source/_posts/A.md
```
--- 
title: Medical Device for foot pressure 
date: 2018-04-03 19:57:46 
tags: Sensor 
cover_index: /images/Medical Device.jpg 
importance: 5 
---
```


/Users/weijiawu/blog/source/_posts/B.md
```
---
title: Self-Balance Bike with Inverted Pendulum
date: 2018-04-02 12:13:09
tags:

Control
Robotics
cover_index: /images/Inverted Pendulum Cover.jpg
importance: 7
---
```

/Users/weijiawu/blog/themes/phantom/layout/index.ejs
```
<header>
    <h1><%- theme.subtitle_main %></h1>
    <p><%- theme.susbtitle_secondary %></p>
</header>

<section class="tiles">
   <%
       // Fast array clone
       var sortedPosts = page.posts.slice(0);
       sortedPosts.sort(function(a, b){
         return a.importance < b.importance
       });
   %>
   <% sortedPosts.forEach(function(item, index){ %>
       <%- partial('_partial/article-index', {item: item, index: index}) %>
   <% }); %>
</section>

<%- partial('_partial/pagination') %>
```

**Comment by klugjo** [comment]
Have you tried `return a.importance > b.importance `

**Comment by wuweijia1994** [comment]
Yes, I tried but still failed.

**Comment by wuweijia1994** [comment]
I suddenly know how to solve it! Just in the "_config.yml" and change the section"order_by: -date" to "order_by: -importance". Then it is solved!
