### ISSUE TITLE
Using custom grid with markdown in posts and pages

### ISSUE THREAD

**Issue by brian-whitfield** [klugjo/hexo-theme-phantom#28]
I'm struggling with figuring out a way to use grids/columns with markdown. Does this theme support this?

I would essentially hope to include something like this...

```
<div class="col-6">
## Intro
</div>
<div class="col-6">
Some info...
</div>
```

**Comment by klugjo** [comment]
Markdown does not support 12 columns grid by default.

But it does support tables. Example:
```
| Table Header 1 | Table Header 2 | Table Header 3 |
| - | - | - |
| Division 1 | Division 2 | Division 3 |
| Division 1 | Division 2 | Division 3 |
| Division 1 | Division 2 | Division 3 |
```

Otherwise for this theme in particular, you will have to dig into the theme's css.

**Comment by brian-whitfield** [comment]
I see, thanks for the clarification. I'll play around with it a little bit.
