### ISSUE TITLE
About.html

### ISSUE THREAD

**Issue by MishaTyupa** [klugjo/hexo-theme-phantom#3]
Hey man.Great theme but I have a problem with about.html. Issue is: Cannot GET /about.html .
Can you figure it out?

**Comment by klugjo** [comment]
Hi did you manage to fix this ?

You can configure the menu in the theme's _config.yml and put whatever link you want there.

The about.html page need to be created by yourself in the page folder of your blog's source

I hope that makes sense.

**Comment by MishaTyupa** [comment]
Yes,I have managed this issue that's why I already closed it.Thanks.
I had a problem with adding an new ejs page to phantom and give this page
url in theme config.yml. Maybe you can give me an advice how to get it to
work..

2016-04-20 6:19 GMT+03:00 Klughertz Jonathan notifications@github.com:

**Comment by klugjo** [comment]
Hi,

I am not sure why you want to add a new ejs page. 

You need to add a new page in the page folder of your blog source. Once your website is up and running, check the URL of the page and add it to the theme's menu.

**Comment by MishaTyupa** [comment]
Ok, I have created page folder in theme's source directory and add it to
router in theme's config.yml.As the result I've got a needed page, but
there is no stylesheets on it just poor html structure on the page..just
trying to make it out

2016-04-22 16:59 GMT+03:00 Klughertz Jonathan notifications@github.com:

**Comment by klugjo** [comment]
Hi,

You need to create a page folder in the main source of your blog (not the themes folder). The same source folder that contains the `_posts` folder. Also, the page should be in markdown format: for example: `about.md`. Same format as posts.

So you will have 

[root of hexo blog] / source / page / about.md

and not

[root of blog] / themes / phantom / source / page / about.html

run `hexo server` and go to localhost:4000/about.html

Hope that helps

**Comment by MishaTyupa** [comment]
Yes,brilliant.Works like a charm.Thanks.
Where to put html code for about.html page?After "hexo generate" in
"public" folder?

2016-04-23 3:25 GMT+03:00 Klughertz Jonathan notifications@github.com:

**Comment by klugjo** [comment]
After your do `hexo generate`, all the files will be placed in the public folder yes.

Take all the HTML files in public folder and upload to your site. The rest of the files (source and themes and all) is only used for generation.

**Comment by MishaTyupa** [comment]
yes,thank you.
This db.json is hard-core a bit:) db on the client.Will be great to connect
hexo theme with postgres sql to generate secure data... .

2016-04-23 10:34 GMT+03:00 Klughertz Jonathan notifications@github.com:
