### ISSUE TITLE
how to config a favicon for website.

### ISSUE THREAD

**Issue by geekeritcom** [klugjo/hexo-theme-phantom#32]
Beautiful theme!
Now I want to set a favicon to my website,but I don't know how to config it.
Hope u reply to me .

**Comment by klugjo** [comment]
Go to head.ejs

and add a favicon like you would for any other website

https://github.com/klugjo/hexo-theme-phantom/blob/master/layout/_partial/head.ejs

**Comment by geekeritcom** [comment]
Thank you very much, this solved my problem.

**Comment by klugjo** [comment]
Cool :)
