### ISSUE TITLE
Post Request

### ISSUE THREAD

**Issue by MishaTyupa** [klugjo/hexo-theme-phantom#5]
Hi!
I have created contact us form for Hexo Blog and looking for opportunity to integrate this framefork with some cloud database to create post requests to store incoming emails, but phantom has only db.json on the root of hexo's directory.Where to store incoming emails in hexo framework?

Thanks

**Comment by klugjo** [comment]
Hi,

Hexo is a static blgo generator, there is no way to store anything once the blog is deployed,

Hexo will use the theme and markdown files to generate pure HTML + CSS. There is no db once deployed, a temporary db is created during the generation, but that is all
