### ISSUE TITLE
why not display Posts and Pages Dates? 

### ISSUE THREAD

**Issue by cyberspaceinfo** [klugjo/hexo-theme-phantom#7]
hi, Jonathan Klughertz. I like this theme. It's the most beautiful theme I've ever seen. But just one little question, why don't you display dates in a post or a page? I think that's necessary. 
Hope to hear from you!

**Comment by klugjo** [comment]
Hi @cyberspaceinfo,

Thanks for your suggestion. I have added the possibility to display dates for posts and pages.

Please get the latest version and see if it works for you.

I have also updated the doc accordingly: https://github.com/klugjo/hexo-theme-phantom#show-dates
