### ISSUE TITLE
Can i add a menu called tags or categories in the menu?

### ISSUE THREAD

**Issue by liky88** [klugjo/hexo-theme-phantom#8]
Can i add a menu called tags or categories in the menu? 

i tried to set it like the about menu. For example, it does not seem to work for tags menu, it won't show out all the tags.

**Comment by klugjo** [comment]
Unfortunately there is no such page. It is a limitation of Hexo, not the Phantom theme.

One way to do it would be to create a plugin, something like this tag cloud https://github.com/MikeCoder/hexo-tag-cloud that displays a list of tags.

Then insert it on a custom page and link to it from the menu

Good luck, if you don't know how to do that, I could help you work on it
